// https://projecteuler.net/problem=2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import (
	"fmt"
	"time"
)

func main() {
	total := 2
	current := 1
	next := 2
	fib := 0
	for fib < 4000000 {
		fib = current + next
		time.Sleep(20 * time.Millisecond)
		current = next
		next = fib
		if fib%2 == 0 {
			total += fib
			fmt.Println(fib)
		}
	}
	fmt.Println(total)
}
